name: 'radar-action'

description: 'Radar GitHub Action for Static Analysis'

inputs:
  path:  
    description: 'Path of the folder to be scanned'
    required: false
    default: '.'
  ignore:  
    description: 'Severities to be ignored (e.g. low,medium)'
    required: false
    default: ''
    
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run entrypoint.sh
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh ${{ inputs.path }} ${{ inputs.ignore }}

branding:
  icon: 'git-pull-request'
  color: 'purple'